version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 clickclash.asgi:channel_layer
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  worker:
    build: .
    command: python manage.py runworker
    volumes:
      - .:/code
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
